name: Build and deploy
on:
  push:
    branches: [ main ]
jobs:
  create-deployment-artifacts:
    name: Create Deployment Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and JS
        run: |
          npm install
          npm run build

      - name: Create deployment Artifact
        run: tar -czf ${{ github.sha }}.tar.gz --exclude=*.git --exclude=node_modules *

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER }}
          key: ${{secrets.SSH_KEY}}
          source: ${{ github.sha }}.tar.gz
          target: /var/www/html/artifacts

      - name: Extract Archive and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{github.sha}}
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USER }}
          envs: GITHUB_SHA
          script: |
            mkdir -p "/var/www/html/releases/${GITHUB_SHA}"
            tar xzf /var/www/html/artifacts/${GITHUB_SHA}.tar.gz -C "/var/www/html/releases/${GITHUB_SHA}"

      - name: Activate Release
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{github.sha}}
          BASE_PATH: /var/www/html
          RELEASE_PATH: /var/www/html/releases/${{github.sha}}
          ACTIVE_PATH: /var/www/html/latest
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USER }}
          envs: GITHUB_SHA,BASE_PATH,RELEASE_PATH,ACTIVE_PATH
          script: |
            ln -s -f ${BASE_PATH}/.env ${RELEASE_PATH}
            ln -s -f $STORAGE_PATH $RELEASE_PATH
            ln -s -n -f $RELEASE_PATH $ACTIVE_PATH

      - name: Cleanup
        uses: appleboy/ssh-action@master
        env:
          RELEASE_PATH: /var/www/html/releases
          ARTIFACTS_PATH: /var/www/html/artifacts
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USER }}
          envs: RELEASE_PATH,ARTIFACTS_PATH
          script: |
            cd $RELEASE_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
            cd $ARTIFACTS_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
